### ISSUE TITLE
Failing Tets in ClubServiceTest

### ISSUE THREAD

**Issue by flouou** [flouou/tournament-organizer#5]
Tests in ClubServiceTest fail when running mvn clean install locally. Runs fine with travis ci.

**Comment by NyorJa** [comment]
Hi @flouou ,

Let me check this issue.

**Comment by AlistairMcKellar** [comment]
I've submitted a pull request with a fix for the issue.

**Comment by NyorJa** [comment]
Hi @flouou ,

Just checked locally by running clean install and its working on my side. Please provide screenshots for the error.

**Comment by NyorJa** [comment]
Hi @flouou ,

Is it ok we can make some other pull request? Like some minor code quality?

**Comment by flouou** [comment]
Hey guys,
thanks for helping out! I have attached a screenshot of the failing test. Sadly the problem is still not resolved with @CGAura 's fix, so I will be leaving this issue open until i have tested it on another machine.
![image](https://user-images.githubusercontent.com/8920423/95020630-8c98f080-066c-11eb-91ec-50073c1e1dfc.png)

**Comment by AlistairMcKellar** [comment]
Interesting, for me the tests didn't run locally at all at first.  Didn't have any failing tests post change.   Wonder what's up there.

**Comment by NyorJa** [comment]
> Interesting, for me the tests didn't run locally at all at first. Didn't have any failing tests post change. Wonder what's up there.

yeah.interisting 👍

**Comment by NyorJa** [comment]
can you share your mvn -v?

**Comment by NyorJa** [comment]
im using java 11 but i think your spring version will be compatible in 14
![image](https://user-images.githubusercontent.com/8148370/95021164-ebc52800-06a1-11eb-88bd-830306185631.png)
![image](https://user-images.githubusercontent.com/8148370/95021190-10b99b00-06a2-11eb-8db5-154eabe82300.png)


not sure if this is JDK related since i observe in your pom you did not define what java version it is

**Comment by AlistairMcKellar** [comment]
JDK 15, and Maven 3.6.3

**Comment by AlistairMcKellar** [comment]
POM has java version 11 defined @NyorJa

**Comment by NyorJa** [comment]
> JDK 15, and Maven 3.6.3

that would be the culprit, try to use at least jdk 11..try to update your maven variables

**Comment by DyspC** [comment]
Hi, 

I looked into your problem and am submitting a fixing PR where I'm detailing the cause.
